name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  format:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: install uv
      uses: astral-sh/setup-uv@v4
      with:
        version: "0.5.9"

    - name: ruff check
      run: uv run ruff check

    - name: ruff format --check
      run: uv run ruff format --check

  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.10", "3.11", "3.12", "3.13"]

    steps:
    - uses: actions/checkout@v4

    - name: install uv
      uses: astral-sh/setup-uv@v4
      with:
        version: "0.5.9"
        enable-cache: true
        cache-dependency-glob: "uv.lock"

    - name: install python
      run: uv python install ${{ matrix.python-version }}

    - run: uv sync --all-extras --dev

    - name: cache huggingface
      uses: actions/cache@v4
      with:
        path: ~/.cache/huggingface
        key: ${{ runner.os }}-hf-models-${{ hashFiles('**/lockfiles') }}
        restore-keys: |
          ${{ runner.os }}-hf-models-

    - run: uv run pytest
